### ISSUE TITLE
Error: failed to download "eks/aws-load-balancer-controller"

### ISSUE THREAD

**Issue by kwonyulchoi** [neilkuan/eks-mgng-tagging-name#140]
When I try to deploy cdk8s in AWS CDK Stack, I experienced the following error message.
Could you check this issue?

------ aws cdk codes in stack -----
const sa = new eks.ServiceAccount(this, 'ALBIRSA', {
            cluster: props.eksCluster,
            namespace: 'kube-system',
            name: 'aws-load-balancer-controller',
        });
 AwsLoadBalancePolicy.addPolicy(VersionsLists.AWS_LOAD_BALANCER_CONTROLLER_POLICY_V2, sa.role);
  const myChart = new MyChartV2(new cdk8s.App(), 'ALBChart', {
            clusterName: props.eksCluster.clusterName,
        });
 const addCdk8sChart = props.eksCluster.addCdk8sChart('my-chart', myChart);
 addCdk8sChart.node.addDependency(sa);

------cdk list result-----------
cdk list EskClusterStack
**Error: failed to download "eks/aws-load-balancer-controller"**

Subprocess exited with error 1
-----------------------

**Comment by neilkuan** [comment]
Hi @kwonyulchoi , thanks for raising this issue.

Before you run `cdk list EskClusterStack`,  please install `helm` in your computer and run
- `helm repo add eks https://aws.github.io/eks-charts`
- `helm repo`
 


[source](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html)

**Comment by kwonyulchoi** [comment]
Thanks for your response.

After completing the following commands, I can deploy this cdk8s construct.


1. helm repo add eks https://aws.github.io/eks-charts
2. helm repo update
3. kubectl apply \
    --validate=false \
    -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml

I wonder if this construct requires cert-manager, or install that instead of us automatically.

**Comment by neilkuan** [comment]
Right, but this repo only for demo.

And eks.Cluster always support create AWS load balancer controller.  

See this docs https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.AlbController.html.

**Comment by kwonyulchoi** [comment]
Thank you very much!!
