### ISSUE TITLE
AWS CDK version2 support?

### ISSUE THREAD

**Issue by kwonyulchoi** [neilkuan/eks-mgng-tagging-name#142]
As you know, "import" statement of AWS CDK version2 is changed.
For example,
@aws-cdk/aws-iam ==> aws-cdk-lib/aws-iam 

When I'm trying to deploy this construct using AWS CDK version2, I found the following error message:

---
Cannot find module ***'@aws-cdk/aws-iam'***
Require stack:
- /Users/............../node_modules/cdk8s-aws-load-balancer-controller/lib/alb-controller-policy.js
- /Users/............../node_modules/cdk8s-aws-load-balancer-controller/lib/index.js
...
...
---

Do you have a plan to support AWS CDK Version2?

**Comment by neilkuan** [comment]
Yes, cdk8s-aws-load-balancer not support aws-cdk V2. 

But you can remove this library. 
Use https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.AlbController.html
 this way to help you create it.

**Comment by kwonyulchoi** [comment]
Thanks a lot.

For reference, "cdk8s-plus" is also very useful and simple.
